export const CRAWL_MAX_CONCURRENCY = 1;
export const CRAWL_MAX_RETRIES = 1;
export const CRAWL_REQUEST_TIMEOUT_SECS = 25;
export const CRAWL_HANDLER_TIMEOUT_SECS = 30;
export const CRAWL_MAX_INDEX_PAGES = 2;
export const CRAWL_MAX_REQUESTS_PER_MINUTE = 12;

export const BOI_SOURCE_APPROVAL_ENV = 'SCOUVELA_BOI_SOURCE_APPROVED';
export const TEF_SOURCE_APPROVAL_ENV = 'SCOUVELA_TEF_SOURCE_APPROVED';
export const GEA_SOURCE_APPROVAL_ENV = 'SCOUVELA_GEA_SOURCE_APPROVED';
export const KCIC_SOURCE_APPROVAL_ENV = 'SCOUVELA_KCIC_SOURCE_APPROVED';
