export const CRAWL_MAX_CONCURRENCY = 1;
export const CRAWL_MAX_RETRIES = 1;
export const CRAWL_REQUEST_TIMEOUT_SECS = 25;
export const CRAWL_HANDLER_TIMEOUT_SECS = 30;
export const CRAWL_MAX_INDEX_PAGES = 2;
export const CRAWL_MAX_REQUESTS_PER_MINUTE = 12;

export const FUNDING_SOURCE_APPROVAL_ENV = 'SCOUVELA_FUNDING_SOURCE_APPROVED';
export const VENDOR_SOURCE_APPROVAL_ENV = 'SCOUVELA_VENDOR_SOURCE_APPROVED';
