/*
 * Demo data only. These records are fictional sample listings for the hackathon UI.
 * They are not scraped, not affiliated with real programmes, and should not be
 * presented as live opportunities. Source URLs point at example.com placeholders.
 */
import type { FundingOpportunity, Vendor } from '@scouvela/shared';

const DEMO_SOURCE = 'Scouvela demo dataset';

export type MockFundingOpportunity = Omit<FundingOpportunity, 'kind'> & {
  businessCategory?: string;
};

export type MockVendor = Omit<Vendor, 'kind'>;

export const MOCK_FUNDING: MockFundingOpportunity[] = [
  {
    id: 'funding-northbridge-working-capital',
    title: 'Northbridge Working Capital Window',
    provider: 'Northbridge Credit Desk',
    fundingType: 'loan',
    amount: 'Up to ₦8 million',
    eligibility: ['Registered Nigerian SME', 'Trading for at least 12 months'],
    deadline: '2026-12-15',
    status: 'active',
    location: 'Lagos',
    description:
      'Short-term working capital for retail and trade businesses that need to restock or cover operating costs.',
    sourceUrl: 'https://example.com/demo/funding/northbridge-working-capital',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-21T08:00:00.000Z',
    businessCategory: 'Retail and trade',
  },
  {
    id: 'funding-harbourlight-growth-grant',
    title: 'Harbourlight Growth Grant',
    provider: 'Harbourlight Enterprise Fund',
    fundingType: 'grant',
    amount: '₦1.5 million seed grant',
    eligibility: ['Women-led micro enterprise', 'Food or hospitality operator'],
    deadline: '2026-09-30',
    status: 'closing-soon',
    location: 'Lagos',
    description:
      'A small grant for food and hospitality founders preparing to expand a neighbourhood operation.',
    sourceUrl: 'https://example.com/demo/funding/harbourlight-growth-grant',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-19T11:20:00.000Z',
    businessCategory: 'Food and hospitality',
  },
  {
    id: 'funding-brightforge-accelerator',
    title: 'BrightForge Founder Accelerator',
    provider: 'BrightForge Lab',
    fundingType: 'accelerator',
    amount: 'Training, mentoring and ₦2 million seed support',
    eligibility: ['Early-stage technology venture', 'Founder based in Nigeria'],
    deadline: '2026-11-20',
    status: 'active',
    location: 'Nigeria',
    description:
      'A 12-week accelerator for early technology products, with mentoring and a modest seed package.',
    sourceUrl: 'https://example.com/demo/funding/brightforge-accelerator',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-18T09:15:00.000Z',
    businessCategory: 'Technology',
  },
  {
    id: 'funding-cassava-belt-grant',
    title: 'Cassava Belt Processing Grant',
    provider: 'Greenfield Agro Window',
    fundingType: 'grant',
    amount: 'Equipment support up to ₦5 million',
    eligibility: ['Small agro-processor', 'Able to show offtake demand'],
    deadline: '2026-10-02',
    status: 'closing-soon',
    location: 'Ogun',
    description:
      'Support for small processors in agriculture who need packaging or milling equipment.',
    sourceUrl: 'https://example.com/demo/funding/cassava-belt-grant',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-17T14:00:00.000Z',
    businessCategory: 'Agriculture',
  },
  {
    id: 'funding-market-square-support',
    title: 'Market Square Business Support Desk',
    provider: 'Market Square Commons',
    fundingType: 'support-programme',
    eligibility: ['Market-based trader', 'Willing to attend bookkeeping clinics'],
    deadline: '2027-01-31',
    status: 'active',
    location: 'Lagos',
    description:
      'A support programme offering record-keeping clinics, supplier introductions and stall-improvement advice.',
    sourceUrl: 'https://example.com/demo/funding/market-square-support',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-16T08:40:00.000Z',
    businessCategory: 'Retail and trade',
  },
  {
    id: 'funding-cedar-micro-loan',
    title: 'Cedar Micro Loan Window',
    provider: 'Cedar Cooperative Desk',
    fundingType: 'loan',
    status: 'unverified',
    location: 'Kano',
    description:
      'A cooperative-style loan listing with incomplete public details. Confirm every term at the original source before applying.',
    sourceUrl: 'https://example.com/demo/funding/cedar-micro-loan',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-15T16:05:00.000Z',
    businessCategory: 'Manufacturing',
  },
  {
    id: 'funding-savannah-export-window',
    title: 'Savannah Export Readiness Window',
    provider: 'Savannah Trade Office',
    fundingType: 'support-programme',
    amount: 'Export coaching and documentation support',
    eligibility: ['Product business with export intent'],
    deadline: '2026-12-01',
    status: 'active',
    location: 'Federal Capital Territory',
    description:
      'Coaching for founders who want to package goods for regional trade, including labelling and documentation clinics.',
    sourceUrl: 'https://example.com/demo/funding/savannah-export-window',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-14T10:00:00.000Z',
    businessCategory: 'Logistics',
  },
  {
    id: 'funding-oakline-asset-finance',
    title: 'Oakline Equipment Finance',
    provider: 'Oakline Asset Desk',
    fundingType: 'loan',
    amount: 'Asset finance from ₦3 million',
    deadline: '2027-02-28',
    status: 'active',
    location: 'Rivers',
    description:
      'Equipment finance aimed at small manufacturers. Eligibility details were not published on the demo source page.',
    sourceUrl: 'https://example.com/demo/funding/oakline-asset-finance',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-12T12:25:00.000Z',
    businessCategory: 'Manufacturing',
  },
  {
    id: 'funding-riverbend-trade-support',
    title: 'Riverbend Women in Trade Support',
    provider: 'Riverbend Commons',
    fundingType: 'support-programme',
    amount: 'Mentoring and a ₦400,000 stipend',
    eligibility: ['Woman-owned fashion or textiles micro business'],
    deadline: '2026-11-05',
    status: 'active',
    description:
      'Mentoring, pricing workshops and a small stipend for fashion and textiles founders.',
    sourceUrl: 'https://example.com/demo/funding/riverbend-trade-support',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-10T09:00:00.000Z',
    businessCategory: 'Fashion and textiles',
  },
  {
    id: 'funding-civicseed-community-grant',
    title: 'CivicSeed Community Learning Grant',
    provider: 'CivicSeed Trust',
    fundingType: 'grant',
    amount: '₦750,000',
    eligibility: ['Community education project', 'Registered organisation or cooperative'],
    deadline: '2026-08-01',
    status: 'expired',
    location: 'Oyo',
    description:
      'A closed education grant kept in the demo set so expired records can be reviewed without being presented as open.',
    sourceUrl: 'https://example.com/demo/funding/civicseed-community-grant',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-08T07:30:00.000Z',
    businessCategory: 'Education',
  },
  {
    id: 'funding-harmattan-creative-lab',
    title: 'Harmattan Creative Lab Call',
    provider: 'Harmattan Rooms',
    fundingType: 'accelerator',
    status: 'unverified',
    location: 'Lagos',
    sourceUrl: 'https://example.com/demo/funding/harmattan-creative-lab',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-06T18:45:00.000Z',
    businessCategory: 'Creative and media',
  },
  {
    id: 'funding-island-retail-recovery',
    title: 'Island Retail Recovery Grant',
    provider: 'Island Commerce Desk',
    fundingType: 'grant',
    amount: '₦2 million',
    eligibility: ['Lagos retail business affected by shop downtime'],
    deadline: '2026-07-15',
    status: 'expired',
    location: 'Lagos',
    description:
      'An expired retail recovery listing. It remains visible so users can see how closed programmes are labelled.',
    sourceUrl: 'https://example.com/demo/funding/island-retail-recovery',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-04T13:10:00.000Z',
    businessCategory: 'Retail and trade',
  },
];

export const MOCK_VENDORS: MockVendor[] = [
  {
    id: 'vendor-threadroom-yaba',
    name: 'Threadroom Atelier',
    category: 'tailoring',
    state: 'Lagos',
    locality: 'Yaba',
    address: 'Herbert Macaulay Way, Yaba',
    phone: '+234 801 000 1101',
    website: 'https://example.com/demo/vendors/threadroom-atelier',
    rating: 4.6,
    description: 'Made-to-measure workwear and small-batch aso-ebi finishing for nearby retailers.',
    sourceUrl: 'https://example.com/demo/vendors/threadroom-atelier',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-21T08:30:00.000Z',
    verificationStatus: 'source-listed',
  },
  {
    id: 'vendor-aso-desk-ikeja',
    name: 'Aso Desk Collective',
    category: 'tailoring',
    state: 'Lagos',
    locality: 'Ikeja',
    address: 'Allen Avenue, Ikeja',
    phone: '+234 801 000 1102',
    rating: 4.4,
    description: 'Alterations and uniform sewing for offices and school suppliers.',
    sourceUrl: 'https://example.com/demo/vendors/aso-desk-collective',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-20T15:10:00.000Z',
    verificationStatus: 'source-listed',
  },
  {
    id: 'vendor-crumb-lane-surulere',
    name: 'Crumb Lane Bakery',
    category: 'baking',
    state: 'Lagos',
    locality: 'Surulere',
    address: 'Adeniran Ogunsanya, Surulere',
    phone: '+234 801 000 1201',
    website: 'https://example.com/demo/vendors/crumb-lane-bakery',
    rating: 4.7,
    description: 'Wholesale bread, snack packs and event cakes for neighbourhood retailers.',
    sourceUrl: 'https://example.com/demo/vendors/crumb-lane-bakery',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-20T09:00:00.000Z',
    verificationStatus: 'source-listed',
  },
  {
    id: 'vendor-oven-order-lekki',
    name: 'Oven & Order',
    category: 'baking',
    state: 'Lagos',
    locality: 'Lekki',
    phone: '+234 801 000 1202',
    description: 'Made-to-order pastry trays for offices and small catering jobs.',
    sourceUrl: 'https://example.com/demo/vendors/oven-and-order',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-18T11:40:00.000Z',
    verificationStatus: 'unverified',
  },
  {
    id: 'vendor-last-sole-ikeja',
    name: 'Last Sole Workshop',
    category: 'shoemaking',
    state: 'Lagos',
    locality: 'Ikeja',
    address: 'Opebi Link Road, Ikeja',
    phone: '+234 801 000 1301',
    rating: 4.3,
    description: 'Custom sandals and repairs for boutiques that need small production runs.',
    sourceUrl: 'https://example.com/demo/vendors/last-sole-workshop',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-18T08:20:00.000Z',
    verificationStatus: 'source-listed',
  },
  {
    id: 'vendor-press-colony-yaba',
    name: 'Press Colony',
    category: 'printing',
    state: 'Lagos',
    locality: 'Yaba',
    address: 'Tejuosho, Yaba',
    phone: '+234 801 000 1401',
    website: 'https://example.com/demo/vendors/press-colony',
    rating: 4.5,
    description:
      'Flyers, product labels and short-run packaging prints for campus and market sellers.',
    sourceUrl: 'https://example.com/demo/vendors/press-colony',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-17T13:55:00.000Z',
    verificationStatus: 'source-listed',
  },
  {
    id: 'vendor-island-print-desk',
    name: 'Island Print Desk',
    category: 'printing',
    state: 'Lagos',
    locality: 'Victoria Island',
    address: 'Adeola Odeku, Victoria Island',
    website: 'https://example.com/demo/vendors/island-print-desk',
    description:
      'Business stationery and presentation packs. Phone number was not listed on the demo source.',
    sourceUrl: 'https://example.com/demo/vendors/island-print-desk',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-16T17:05:00.000Z',
    verificationStatus: 'source-listed',
  },
  {
    id: 'vendor-packwell-ikeja',
    name: 'Packwell Desk',
    category: 'packaging',
    state: 'Lagos',
    locality: 'Ikeja',
    address: 'Ogba, Ikeja',
    phone: '+234 801 000 1501',
    rating: 4.2,
    description: 'Cartons, mailer bags and bottle sleeves for consumer-goods startups.',
    sourceUrl: 'https://example.com/demo/vendors/packwell-desk',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-16T10:15:00.000Z',
    verificationStatus: 'source-listed',
  },
  {
    id: 'vendor-wrap-label-yaba',
    name: 'Wrap & Label Co',
    category: 'packaging',
    state: 'Lagos',
    locality: 'Yaba',
    phone: '+234 801 000 1502',
    description: 'Sticker rolls and simple product wraps for bakers and soap makers.',
    sourceUrl: 'https://example.com/demo/vendors/wrap-and-label-co',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-14T12:00:00.000Z',
    verificationStatus: 'unverified',
  },
  {
    id: 'vendor-lightcraft-lekki',
    name: 'Lightcraft Studio',
    category: 'photography',
    state: 'Lagos',
    locality: 'Lekki',
    address: 'Admiralty Way, Lekki',
    phone: '+234 801 000 1601',
    website: 'https://example.com/demo/vendors/lightcraft-studio',
    rating: 4.8,
    description: 'Product photography and lookbooks for small fashion and food brands.',
    sourceUrl: 'https://example.com/demo/vendors/lightcraft-studio',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-13T09:45:00.000Z',
    verificationStatus: 'source-listed',
  },
  {
    id: 'vendor-table-service-surulere',
    name: 'Table Service Kitchen',
    category: 'catering',
    state: 'Lagos',
    locality: 'Surulere',
    address: 'Bode Thomas, Surulere',
    phone: '+234 801 000 1701',
    rating: 4.4,
    description: 'Office lunch packs and small event catering with vegetarian options.',
    sourceUrl: 'https://example.com/demo/vendors/table-service-kitchen',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-12T14:20:00.000Z',
    verificationStatus: 'source-listed',
  },
  {
    id: 'vendor-room-theory-vi',
    name: 'Room Theory',
    category: 'interior-decoration',
    state: 'Lagos',
    locality: 'Victoria Island',
    address: 'Kofo Abayomi, Victoria Island',
    phone: '+234 801 000 1801',
    website: 'https://example.com/demo/vendors/room-theory',
    rating: 4.1,
    description: 'Shop-front styling and simple interior fit-outs for clinics and boutiques.',
    sourceUrl: 'https://example.com/demo/vendors/room-theory',
    sourceName: DEMO_SOURCE,
    discoveredAt: '2026-09-11T08:50:00.000Z',
    verificationStatus: 'source-listed',
  },
];
